spring:
    redis:
      host: goodtime-iot.com
      #cluster:
        #nodes: 172.22.149.107:7003,172.22.149.106:7000,172.22.149.106:7001,172.22.149.106:7002,172.22.149.107:7004,172.22.149.107:7005
        #nodes: 172.19.2.122:7000,172.19.2.122:7001,172.19.2.121:7000,172.19.2.121:7001,172.19.2.120:7000,172.19.2.120:7001
      timeout: 5000 # 连接超时时间（毫秒）
      pool:
        max-active: 1100  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 20     # 连接池中的最大空闲连接
        min-idle: 5     # 连接池中的最小空闲连接 rm-0xi3946z04807h3r95o.mysql.rds.aliyuncs.com
        max-wait: 10000   # 连接池最大阻塞等待时间（使用负值表示没有限制）
